/*
 * File: app/view/MainViewport.js
 * Date: Tue Dec 04 2012 11:30:41 GMT-0600 (CST)
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'MyApp.view.CornPlantSprite',
        'MyApp.view.GrassPlantSprite',
        'MyApp.view.FarmHolderPanel',
        'MyApp.view.FieldHealthPopup',
        'MyApp.view.InformationPanel',
        'MyApp.view.ContractPanel',
        'MyApp.view.Field',
        'MyApp.view.Farm'
    ],

    autoScroll: true,
    layout: {
        type: 'fit'
    },

    title: 'My Window',

	//--------------------------------------------------------------------------
    initComponent: function() {
        var me = this;        
        
        Ext.applyIf(me, {
            items: [{
				xtype: 'panel',
				layout: {
					type: 'fit'
				},
				dockedItems: [{
						xtype: 'panel',
						dock: 'top',
						height: 50,
						width: 200
				}],
				items: [{
					xtype: 'panel',
					layout: {
						type: 'column'
					},
					bodyStyle: 'background-image: url(app/assets/site_bg.jpg); background-size: cover; background-repeat: no-repeat; background-attachment: fixed; background-position: center top;',
					items: [{
							xtype: 'panel',
							columnWidth: 0.5
						},
						{
							xtype: 'farmHolderPanel'
						},
						{
							xtype: 'metricsPanel'

					}]
				}]
			}]
        });

        me.callParent(arguments);
    }
});
